### ISSUE TITLE
make fetchstys -> make: *** [algorithm.sty] Error 8

### ISSUE THREAD

**Issue by diehlpk** [latextemplates/uni-stuttgart-computer-science-template#13]
Delivers this error:

wget ftp://dante.ctan.org/tex-archive/macros/latex/contrib/algorithms/algorithm.sty
--2014-04-22 17:28:48--  ftp://dante.ctan.org/tex-archive/macros/latex/contrib/algorithms/algorithm.sty
           => `algorithm.sty'
Resolving dante.ctan.org (dante.ctan.org)... 176.28.54.184, 2a01:488:67:1000:b01c:36b8:0:1
Connecting to dante.ctan.org (dante.ctan.org)|176.28.54.184|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /tex-archive/macros/latex/contrib/algorithms ... done.
==> SIZE algorithm.sty ... done.
==> PASV ... done.    ==> RETR algorithm.sty ... 
No such file `algorithm.sty'.

make: *** [algorithm.sty] Error 8

**Comment by koppor** [comment]
Support of fetchstys has been dropped in c7ffbf5b as current latex distributions include all required packages.
