### ISSUE TITLE
No master branch

### ISSUE THREAD

**Issue by baderas** [latextemplates/uni-stuttgart-computer-science-template#18]
We need to change either the Readme file (says "5. git checkout -b master") or the change the main branch to 'master'. The actual main branch is called 'template' (which should normally be master), there is no 'master'.

**Comment by koppor** [comment]
`git checkout -b master` checks out the `github/template` branch as local branch `master` to ensure that development goes on in the `master` branch. I thought that using a branch name `template` and a branch `master` separates the development of the template without any real content from the actual thesis work. To force that separation, I introduced the thesis branch. Do you think, that's confusing?

**Comment by baderas** [comment]
Sorry, I was confused because I missed "-b" and saw no master branch from origin. Then of course everything works fine.

If you stick to the readme it isn't confusing, I think ;)
