### ISSUE TITLE
make not working anymore?

### ISSUE THREAD

**Issue by baderas** [latextemplates/uni-stuttgart-computer-science-template#19]
is the make file supposed to be working like that?
$ git clone https://github.com/latextemplates/uni-stuttgart-computer-science-template.git
$ cd uni-stuttgart-computer-science-template/
$ make
make: *** No rule to make target 'bibliography/bibliography.bib', needed by 'ausarbeitung.bbl'.  Schluss.
$ make pdf
make: *** No rule to make target 'bibliography/bibliography.bib', needed by 'ausarbeitung.bbl'.  Schluss.

**Comment by diehlpk** [comment]
I would recommend to switch to latexmk (http://users.phys.psu.edu/~collins/software/latexmk-jcc/). It is more comfortable and everything is easier. I have done this switch for the forked template. Then we do not have this problems as described here.

**Comment by baderas** [comment]
I've using my own build.sh, I just tried to use it for reproducing an error (see my other report) and saw that it does not seem to work ootb.

**Comment by diehlpk** [comment]
You should not use your own build script. Because latexmk checks plenty condition to compile your document several times to update everything. 

latexmk -pdf template.tex

and

latexmk -C

Do all what you implement with your own script.

**Comment by baderas** [comment]
Yes, and I can also do that by hand or use rubber to do it ;)

**Comment by diehlpk** [comment]
I think we should start to use latexmk in the make file here too. If there is no disagreement I could push the makefile from the forked repo to this one here.

**Comment by koppor** [comment]
I'm not sure whether a `Makefile` is required at all if latexmk is used. Can latexmk be used in a mode where it stops at the first error?

**Comment by koppor** [comment]
The reason, why `make` stopped working is because 6ea1ed30 moved the `.bib` file.

**Comment by baderas** [comment]
if you plan to change to latexmk, a hint for new users that you can add stuff like makeglossaries via a .latexmkrc file should be given, see http://tex.stackexchange.com/questions/1226/how-to-make-latexmk-use-makeglossaries

**Comment by koppor** [comment]
Switched to latexmk in d2f660a8 and 87fbf860. Works here.
