### ISSUE TITLE
glossaries support for abbreviation

### ISSUE THREAD

**Issue by soriak** [latextemplates/uni-stuttgart-computer-science-template#3]
What is intended way to add abbreviations? I'm using the glossaries package right now. If needed I can provide the changes in ausarbeitung.tex, packages_and_options.tex and Makefile. Otherwise I would like to know whats best practice for abbreviations using the template.

**Comment by TwinbrotherPro** [comment]
I'm currently searching for a solution using abbreviations in my thesis. 

I found this code in the [packages_and_options.tex](https://github.com/latextemplates/uni-stuttgart-computer-science-template/blob/template/preambel/packages_and_options.tex):

`%%%
%lustiger Hack fuer das Abkuerzungsverzeichnis
%nach latex durchlauf folgendes ausfuehren
%makeindex ausarbeitung.nlo -s nomencl.ist -o ausarbeitung.nls
%danach nochmal latex
%\usepackage{nomencl}
%    \let\abk\nomenclature %Deutsche Ueberschrift setzen
%          \renewcommand{\nomname}{List of Abbreviations}
%        %Punkte zw. Abkuerzung und Erklaerung
%          \setlength{\nomlabelwidth}{.2\hsize}
%          \renewcommand{\nomlabel}[1]{#1 \dotfill}
%        %Zeilenabstaende verkleinern
%          \setlength{\nomitemsep}{-\parsep}
%    \makenomenclature
%
%%%`

I tried to use it but, although makeindex is writing something in my .nls-File nothing happens in my pdf-file. (I am recompiling it with PDFLatex after the recommended makeIndex command)

My Questions:
Is there still no recommendation? How does this hack work? How do I use it?

**Comment by koppor** [comment]
We currently use the acronym package (thanks to @SamyStyle), but we are discussing to switch to glossaries (see #35). Both the current master and the PR contain examples. @TwinbrotherPro That should solve your issues, doesn't it?
