### ISSUE TITLE
ausarbeitung.synctex(busy) file is not on .gitignore 

### ISSUE THREAD

**Issue by eiselems** [latextemplates/uni-stuttgart-computer-science-template#37]
At least this file gets generated on my windows machine instead o the normal         ausarbeitung.synctex.gz(busy).

I had a look at https://github.com/github/gitignore/blob/master/TeX.gitignore and saw that it is also listed in there.

Think it should be ok to add it `.gitignore`
Any reasons not to add it?

**Comment by koppor** [comment]
Follow up: I included all updates from https://www.gitignore.io/api/latex,jabref,microsoftoffice,libreoffice,emacs in 843c5904fe616b256cfce1cec0dbfc68d60e6cbe. Thank you for the reminder.
