### ISSUE TITLE
Fachstudie kann im Template nicht angegeben werden

### ISSUE THREAD

**Issue by googol42** [latextemplates/uni-stuttgart-computer-science-template#39]
Beim Erstellen einer Arbeit gibt man diplom, study, bachelor, master oder projectinf an. In Zeile 145 (https://github.com/latextemplates/uni-stuttgart-computer-science-template/blob/template/uni-stuttgart-cs-cover.sty#L145) ist ein Label "Fachstudie" definiert. Die Angabe 'fachstudie' jedoch fehlt; gibt man sie so an, steht auf dem Deckblatt "fachstudie nr" - quasi genauso wie man es angibt.

**Comment by koppor** [comment]
Should be fixed.

@kmindi Should we port that to https://github.com/latextemplates/uni-stuttgart-computer-science-cover?

**Comment by kmindi** [comment]
Ported (latextemplates/uni-stuttgart-computer-science-cover/commit/ed6fd3b69bfbb75ce8158996bdf710078b5f325d)
