### ISSUE TITLE
List of Abbreviations wrong position

### ISSUE THREAD

**Issue by SamyStyle** [latextemplates/uni-stuttgart-computer-science-template#42]
List of Abbreviations is at the end of the thesis, this cannot be the correct way since all other lists are at the beginning right after the table of content.

**Comment by koppor** [comment]
@baderas Could you have a look? Refs #43

**Comment by koppor** [comment]
Solved in #45 by replacing the code of http://tex.stackexchange.com/questions/145579/how-to-print-acronyms-of-glossaries-into-a-table by `\makenoidxglossaries`.

See https://github.com/latextemplates/uni-stuttgart-computer-science-template/pull/45/commits/c2b102e52542f731bb944c056597effb8c9909a7

**Comment by baderas** [comment]
Wieso sagst du mir gestern dass das erledigt ist und revertest nun
einfach mal Code den ich mühsam aus meiner DA da rein portiert hab, der
problemlos funktioniert und uns eine schöne Abkürzungstabelle erzeugt?

Am 14.10.2016 um 09:49 schrieb Oliver Kopp:
