### ISSUE TITLE
Double column template

### ISSUE THREAD

**Issue by koppor** [latextemplates/uni-stuttgart-computer-science-template#46]
@SGrottel-TUD once told me that he used two column layout in his thesis, because the lines are too long on an A4 page. Should we also switch to a two-column layout in the thesis? Maybe aligned to the IEEE template?

**Comment by SamyStyle** [comment]
I strictly argue against a double column template. I also discussed this quickly with my colleagues. Common sense is that the thesis should look like a book.
The IEEE or ACM double column template is nice for a 10 pager but not for a 80 page thesis.

**Comment by koppor** [comment]
Hint for Koma script: http://www.komascript.de/node/759
